name: Fetch Reddit Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Get Python 3.12
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.12'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 aiohttp

      - name: Update README file
        run: python daily.py

      - name: Commit and push data.json
        run: |
          git config --global user.name "pyoneerC/GitHub-Actions-Bot"
          git config --global user.email "github-actions-bot@pyoneerc.github.io" 
          git add .
          git diff
          git commit -m "Update JSON" -a || echo "No changes to commit"
          git push

      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '7 days'